const monstersArea1 = {
  slimes: [
    {
      name: "Fire Slime",
      level: 1,
      power: 5,
      health: 15,
      immune: ["fire"],
      resistant: ["earth"],
      weakness: ["water"],
      neutral: ["normal"],
    },
    {
      name: "Water Slime",
      level: 1,
      power: 5,
      health: 15,
      immune: ["water"],
      resistant: ["fire"],
      weakness: ["earth"],
      neutral: ["normal"],
    },
    {
      name: "Metal Slime",
      level: 2,
      power: 6,
      health: 20,
      immune: ["earth"],
      resistant: ["water"],
      weakness: ["fire"],
      neutral: ["normal"],
    },
  ],
  wizards: [
    {
      name: "Flame Wizard",
      level: 12,
      power: 20,
      health: 120,
      immune: ["fire"],
      resistant: ["earth"],
      weakness: ["water"],
      neutral: ["normal"],
    },
    {
      name: "Ice Sorcerer",
      level: 10,
      power: 16,
      health: 100,
      immune: ["water"],
      resistant: ["fire"],
      weakness: ["earth"],
      neutral: ["normal"],
    },
    {
      name: "Shaman",
      level: 11,
      power: 18,
      health: 110,
      immune: ["earth"],
      resistant: ["water"],
      weakness: ["fire"],
      neutral: ["normal"],
    },
  ],
  elementals: [
    {
      name: "Blaze Elemental",
      level: 20,
      power: 6,
      health: 200,
      immune: ["fire"],
      resistant: ["earth"],
      weakness: ["water"],
      neutral: ["normal"],
    },
    {
      name: "Blizzard Elemental",
      level: 20,
      power: 6,
      health: 200,
      immune: ["water"],
      resistant: ["fire"],
      weakness: ["earth"],
      neutral: ["normal"],
    },
    {
      name: "Earth Elemental",
      level: 20,
      power: 6,
      health: 200,
      immune: ["earth"],
      resistant: ["water"],
      weakness: ["fire"],
      neutral: ["normal"],
    },
  ],
  //random encounters below
  bandits: [
    {
      name: "Bandit Keith",
      level: 5,
      power: 6,
      health: 70,
      immune: ["none"],
      resistant: ["none"],
      weakness: ["none"],
      neutral: ["normal", "fire", "earth", "water"],
    },
    {
      name: "Quinn Eyepatch",
      level: 10,
      power: 6,
      health: 120,
      immune: ["none"],
      resistant: ["none"],
      weakness: ["none"],
      neutral: ["normal", "fire", "earth", "water"],
    },
    {
      name: "Kerry Crazy Eyes",
      level: 15,
      power: 6,
      health: 170,
      immune: ["none"],
      resistant: ["fire"],
      weakness: ["none"],
      neutral: ["normal", "earth", "water"],
    },
    {
      name: "Thieving Carmen",
      level: 20,
      power: 6,
      health: 230,
      immune: ["none"],
      resistant: ["earth"],
      weakness: ["none"],
      neutral: ["normal", "fire", "water"],
    },
  ],
  wolves: [
    {
      name: "Wolf Alpha",
      level: 5,
      power: 6,
      health: 75,
      immune: ["none"],
      resistant: ["earth"],
      weakness: ["fire"],
      neutral: ["normal", "water"],
    },
    {
      name: "Kiba",
      level: 10,
      power: 6,
      health: 150,
      immune: ["none"],
      resistant: ["earth"],
      weakness: ["fire"],
      neutral: ["normal", "water"],
    },
    {
      name: "White Fang",
      level: 15,
      power: 6,
      health: 275,
      immune: ["none"],
      resistant: ["earth"],
      weakness: ["fire"],
      neutral: ["normal", "water"],
    },
    {
      name: "Ranga",
      level: 20,
      power: 6,
      health: 375,
      immune: ["none"],
      resistant: ["earth"],
      weakness: ["none"],
      neutral: ["normal", "water", "fire"],
    },
  ],
  mimics: [
    {
      name: "Dark Mimic",
      level: 3,
      power: 6,
      health: 75,
      immune: ["none"],
      resistant: ["earth"],
      weakness: ["fire"],
      neutral: ["normal", "water"],
    },
    {
      name: "Mimighoul",
      level: 12,
      power: 18,
      health: 150,
      immune: ["none"],
      resistant: ["earth", "fire"],
      weakness: ["none"],
      neutral: ["normal", "water"],
    },
    {
      name: "Mimiking",
      level: 18,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
  ],
};

const monstersArea2 = {
  demon: [
    {
      name: "Imps",
      level: 35,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire"],
      weakness: ["water"],
      neutral: ["normal"],
    },
    {
      name: "Shadow demon",
      level: 38,
      power: 40,
      health: 400,
      immune: ["normal"],
      resistant: ["fire"],
      weakness: ["water"],
      neutral: ["earth"],
    },
    {
      name: "Incubi",
      level: 36,
      power: 37,
      health: 385,
      immune: ["normal"],
      resistant: ["earth"],
      weakness: ["water"],
      neutral: ["fire"],
    },
  ],
  hellhound: [
    {
      name: "Cerberus pup",
      level: 35,
      power: 45,
      health: 410,
      immune: ["fire", "earth", "normal"],
      resistant: ["none"],
      weakness: ["water"],
      neutral: ["none"],
    },
    {
      name: "hellhound",
      level: 30,
      power: 35,
      health: 375,
      immune: ["none"],
      resistant: ["fire", "normal"],
      weakness: ["water"],
      neutral: ["earth"],
    },
    {
      name: "Nessian Warhounds",
      level: 30,
      power: 35,
      health: 375,
      immune: ["fire"],
      resistant: ["earth", "normal"],
      weakness: ["water"],
      neutral: ["none"],
    },
  ],
  skeleton: [
    {
      name: "Skeleton warrior",
      level: 25,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
    {
      name: "Skeleton lancer",
      level: 25,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
    {
      name: "Skeleton archer",
      level: 25,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
  ],
  //random encounters below
  //need to change stats below
  zombies: [
    {
      name: "Dullahan",
      level: 25,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
    {
      name: "Lich Reaper",
      level: 25,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
    {
      name: "Frankenstein",
      level: 25,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
  ],
  vampires: [
    {
      name: "Dracula",
      level: 25,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
    {
      name: "Nosferatu ",
      level: 25,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
    {
      name: "Nikusui",
      level: 25,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
  ],
  werewolves: [
    {
      name: "Fenrir",
      level: 25,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
    {
      name: "Lycaon",
      level: 25,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
    {
      name: "Marchosias",
      level: 25,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
  ],
};

const monstersArea3 = {
  giant: [
    {
      name: "Polyphemus",
      level: 55,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["normal"],
      weakness: ["fire"],
      neutral: ["water"],
    },
    {
      name: "Surtr",
      level: 55,
      power: 35,
      health: 375,
      immune: ["earth", "fire"],
      resistant: ["normal"],
      weakness: ["water"],
      neutral: ["none"],
    },
    {
      name: "Typhon",
      level: 55,
      power: 35,
      health: 375,
      immune: ["water"],
      resistant: ["normal", "fire"],
      weakness: ["none"],
      neutral: ["earth"],
    },
  ],
  orge: [
    {
      name: "Yeti",
      level: 50,
      power: 35,
      health: 375,
      immune: ["water"],
      resistant: ["normal"],
      weakness: ["fire"],
      neutral: ["earth"],
    },
    {
      name: "Half Ogre",
      level: 50,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["normal"],
      weakness: ["fire"],
      neutral: ["water"],
    },
    {
      name: "Oni",
      level: 50,
      power: 35,
      health: 375,
      immune: ["fire"],
      resistant: ["normal"],
      weakness: ["earth"],
      neutral: ["water"],
    },
  ],
  orc: [
    {
      name: "Ork General",
      level: 45,
      power: 35,
      health: 375,
      immune: ["none"],
      resistant: ["normal", "earth"],
      weakness: ["none"],
      neutral: ["fire", "water"],
    },
    {
      name: "Hobgoblin Berzerker",
      level: 45,
      power: 35,
      health: 375,
      immune: ["none"],
      resistant: ["normal", "fire"],
      weakness: ["water"],
      neutral: ["earth"],
    },
    {
      name: "High Orc",
      level: 45,
      power: 35,
      health: 375,
      immune: ["none"],
      resistant: ["normal", "fire"],
      weakness: ["water"],
      neutral: ["earth"],
    },
  ],
  //random encounters below
  //need to change stats below
  golems: [
    {
      name: "Mecha Construct",
      level: 25,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
    {
      name: "Flesh Golem",
      level: 25,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
    {
      name: "Ice Golem",
      level: 25,
      power: 35,
      health: 375,
      immune: ["water"],
      resistant: ["normal"],
      weakness: ["fire"],
      neutral: ["earth"],
    },
  ],
  behemoth: [
    {
      name: "Behemoth",
      level: 25,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
    {
      name: "Leviathan",
      level: 25,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
    {
      name: "Bahamut",
      level: 25,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
  ],
  titans: [
    {
      name: "Cronos",
      level: 25,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
    {
      name: "Ymir",
      level: 25,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
    {
      name: "Asura",
      level: 25,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
  ],
};

const bossMonsters = [
  {
    name: "Challenger",
    level: 25,
    power: 35,
    health: 375,
    immune: ["earth"],
    resistant: ["fire", "water"],
    weakness: ["none"],
    neutral: ["normal"],
  },
  {
    name: "Normal stranger",
    level: 25,
    power: 35,
    health: 375,
    immune: ["earth"],
    resistant: ["fire", "water"],
    weakness: ["none"],
    neutral: ["normal"],
  },
  {
    name: "Tubby Guard",
    level: 25,
    power: 35,
    health: 375,
    immune: ["earth"],
    resistant: ["fire", "water"],
    weakness: ["none"],
    neutral: ["normal"],
  },
  {
    name: "Dumb, Dumber, and Dumbest",
    level: 25,
    power: 35,
    health: 375,
    immune: ["earth"],
    resistant: ["fire", "water"],
    weakness: ["none"],
    neutral: ["normal"],
  },
];

const allMonsters = {
  area1: {
    slimes: [
      {
        name: "Fire Slime",
        level: 1,
        power: 5,
        health: 15,
        immune: ["fire"],
        resistant: ["earth"],
        weakness: ["water"],
        neutral: ["normal"],
      },
      {
        name: "Water Slime",
        level: 1,
        power: 5,
        health: 15,
        immune: ["water"],
        resistant: ["fire"],
        weakness: ["earth"],
        neutral: ["normal"],
      },
      {
        name: "Metal Slime",
        level: 2,
        power: 6,
        health: 20,
        immune: ["earth"],
        resistant: ["water"],
        weakness: ["fire"],
        neutral: ["normal"],
      },
    ],
    wizards: [
      {
        name: "Flame Wizard",
        level: 12,
        power: 20,
        health: 120,
        immune: ["fire"],
        resistant: ["earth"],
        weakness: ["water"],
        neutral: ["normal"],
      },
      {
        name: "Ice Sorcerer",
        level: 10,
        power: 16,
        health: 100,
        immune: ["water"],
        resistant: ["fire"],
        weakness: ["earth"],
        neutral: ["normal"],
      },
      {
        name: "Shaman",
        level: 11,
        power: 18,
        health: 110,
        immune: ["earth"],
        resistant: ["water"],
        weakness: ["fire"],
        neutral: ["normal"],
      },
    ],
    elementals: [
      {
        name: "Blaze Elemental",
        level: 20,
        power: 6,
        health: 200,
        immune: ["fire"],
        resistant: ["earth"],
        weakness: ["water"],
        neutral: ["normal"],
      },
      {
        name: "Blizzard Elemental",
        level: 20,
        power: 6,
        health: 200,
        immune: ["water"],
        resistant: ["fire"],
        weakness: ["earth"],
        neutral: ["normal"],
      },
      {
        name: "Earth Elemental",
        level: 20,
        power: 6,
        health: 200,
        immune: ["earth"],
        resistant: ["water"],
        weakness: ["fire"],
        neutral: ["normal"],
      },
    ],
    //random encounters below
    bandits: [
      {
        name: "Bandit Keith",
        level: 5,
        power: 6,
        health: 70,
        immune: ["none"],
        resistant: ["none"],
        weakness: ["none"],
        neutral: ["normal", "fire", "earth", "water"],
      },
      {
        name: "Quinn Eyepatch",
        level: 10,
        power: 6,
        health: 120,
        immune: ["none"],
        resistant: ["none"],
        weakness: ["none"],
        neutral: ["normal", "fire", "earth", "water"],
      },
      {
        name: "Kerry Crazy Eyes",
        level: 15,
        power: 6,
        health: 170,
        immune: ["none"],
        resistant: ["fire"],
        weakness: ["none"],
        neutral: ["normal", "earth", "water"],
      },
      {
        name: "Thieving Carmen",
        level: 20,
        power: 6,
        health: 230,
        immune: ["none"],
        resistant: ["earth"],
        weakness: ["none"],
        neutral: ["normal", "fire", "water"],
      },
    ],
    wolves: [
      {
        name: "Wolf Alpha",
        level: 5,
        power: 6,
        health: 75,
        immune: ["none"],
        resistant: ["earth"],
        weakness: ["fire"],
        neutral: ["normal", "water"],
      },
      {
        name: "Kiba",
        level: 10,
        power: 6,
        health: 150,
        immune: ["none"],
        resistant: ["earth"],
        weakness: ["fire"],
        neutral: ["normal", "water"],
      },
      {
        name: "White Fang",
        level: 15,
        power: 6,
        health: 275,
        immune: ["none"],
        resistant: ["earth"],
        weakness: ["fire"],
        neutral: ["normal", "water"],
      },
      {
        name: "Ranga",
        level: 20,
        power: 6,
        health: 375,
        immune: ["none"],
        resistant: ["earth"],
        weakness: ["none"],
        neutral: ["normal", "water", "fire"],
      },
    ],
    mimics: [
      {
        name: "Dark Mimic",
        level: 3,
        power: 6,
        health: 75,
        immune: ["none"],
        resistant: ["earth"],
        weakness: ["fire"],
        neutral: ["normal", "water"],
      },
      {
        name: "Mimighoul",
        level: 12,
        power: 18,
        health: 150,
        immune: ["none"],
        resistant: ["earth", "fire"],
        weakness: ["none"],
        neutral: ["normal", "water"],
      },
      {
        name: "Mimiking",
        level: 18,
        power: 35,
        health: 375,
        immune: ["earth"],
        resistant: ["fire", "water"],
        weakness: ["none"],
        neutral: ["normal"],
      },
    ],
  },
  area2: {
    skeleton: [
      {
        name: "Skeleton warrior",
        level: 25,
        power: 35,
        health: 375,
        immune: ["earth"],
        resistant: ["fire", "water"],
        weakness: ["none"],
        neutral: ["normal"],
      },
      {
        name: "Skeleton lancer",
        level: 25,
        power: 35,
        health: 375,
        immune: ["earth"],
        resistant: ["fire", "water"],
        weakness: ["none"],
        neutral: ["normal"],
      },
      {
        name: "Skeleton archer",
        level: 25,
        power: 35,
        health: 375,
        immune: ["earth"],
        resistant: ["fire", "water"],
        weakness: ["none"],
        neutral: ["normal"],
      },
    ],
    hellhound: [
      {
        name: "Cerberus pup",
        level: 35,
        power: 45,
        health: 410,
        immune: ["fire", "earth", "normal"],
        resistant: ["none"],
        weakness: ["water"],
        neutral: ["none"],
      },
      {
        name: "hellhound",
        level: 30,
        power: 35,
        health: 375,
        immune: ["none"],
        resistant: ["fire", "normal"],
        weakness: ["water"],
        neutral: ["earth"],
      },
      {
        name: "Nessian Warhounds",
        level: 30,
        power: 35,
        health: 375,
        immune: ["fire"],
        resistant: ["earth", "normal"],
        weakness: ["water"],
        neutral: ["none"],
      },
    ],
    demon: [
      {
        name: "Imps",
        level: 35,
        power: 35,
        health: 375,
        immune: ["earth"],
        resistant: ["fire"],
        weakness: ["water"],
        neutral: ["normal"],
      },
      {
        name: "Shadow demon",
        level: 38,
        power: 40,
        health: 400,
        immune: ["normal"],
        resistant: ["fire"],
        weakness: ["water"],
        neutral: ["earth"],
      },
      {
        name: "Incubi",
        level: 36,
        power: 37,
        health: 385,
        immune: ["normal"],
        resistant: ["earth"],
        weakness: ["water"],
        neutral: ["fire"],
      },
    ],
    //random encounters below
    //need to change stats below
    zombies: [
      {
        name: "Dullahan",
        level: 25,
        power: 35,
        health: 375,
        immune: ["earth"],
        resistant: ["fire", "water"],
        weakness: ["none"],
        neutral: ["normal"],
      },
      {
        name: "Lich Reaper",
        level: 25,
        power: 35,
        health: 375,
        immune: ["earth"],
        resistant: ["fire", "water"],
        weakness: ["none"],
        neutral: ["normal"],
      },
      {
        name: "Frankenstein",
        level: 25,
        power: 35,
        health: 375,
        immune: ["earth"],
        resistant: ["fire", "water"],
        weakness: ["none"],
        neutral: ["normal"],
      },
    ],
    vampires: [
      {
        name: "Dracula",
        level: 25,
        power: 35,
        health: 375,
        immune: ["earth"],
        resistant: ["fire", "water"],
        weakness: ["none"],
        neutral: ["normal"],
      },
      {
        name: "Nosferatu ",
        level: 25,
        power: 35,
        health: 375,
        immune: ["earth"],
        resistant: ["fire", "water"],
        weakness: ["none"],
        neutral: ["normal"],
      },
      {
        name: "Nikusui",
        level: 25,
        power: 35,
        health: 375,
        immune: ["earth"],
        resistant: ["fire", "water"],
        weakness: ["none"],
        neutral: ["normal"],
      },
    ],
    werewolves: [
      {
        name: "Fenrir",
        level: 25,
        power: 35,
        health: 375,
        immune: ["earth"],
        resistant: ["fire", "water"],
        weakness: ["none"],
        neutral: ["normal"],
      },
      {
        name: "Lycaon",
        level: 25,
        power: 35,
        health: 375,
        immune: ["earth"],
        resistant: ["fire", "water"],
        weakness: ["none"],
        neutral: ["normal"],
      },
      {
        name: "Marchosias",
        level: 25,
        power: 35,
        health: 375,
        immune: ["earth"],
        resistant: ["fire", "water"],
        weakness: ["none"],
        neutral: ["normal"],
      },
    ],
  },
  area3: {
    orc: [
      {
        name: "Ork General",
        level: 45,
        power: 35,
        health: 375,
        immune: ["none"],
        resistant: ["normal", "earth"],
        weakness: ["none"],
        neutral: ["fire", "water"],
      },
      {
        name: "Hobgoblin Berzerker",
        level: 45,
        power: 35,
        health: 375,
        immune: ["none"],
        resistant: ["normal", "fire"],
        weakness: ["water"],
        neutral: ["earth"],
      },
      {
        name: "High Orc",
        level: 45,
        power: 35,
        health: 375,
        immune: ["none"],
        resistant: ["normal", "fire"],
        weakness: ["water"],
        neutral: ["earth"],
      },
    ],
    orge: [
      {
        name: "Yeti",
        level: 50,
        power: 35,
        health: 375,
        immune: ["water"],
        resistant: ["normal"],
        weakness: ["fire"],
        neutral: ["earth"],
      },
      {
        name: "Half Ogre",
        level: 50,
        power: 35,
        health: 375,
        immune: ["earth"],
        resistant: ["normal"],
        weakness: ["fire"],
        neutral: ["water"],
      },
      {
        name: "Oni",
        level: 50,
        power: 35,
        health: 375,
        immune: ["fire"],
        resistant: ["normal"],
        weakness: ["earth"],
        neutral: ["water"],
      },
    ],
    giant: [
      {
        name: "Polyphemus",
        level: 55,
        power: 35,
        health: 375,
        immune: ["earth"],
        resistant: ["normal"],
        weakness: ["fire"],
        neutral: ["water"],
      },
      {
        name: "Surtr",
        level: 55,
        power: 35,
        health: 375,
        immune: ["earth", "fire"],
        resistant: ["normal"],
        weakness: ["water"],
        neutral: ["none"],
      },
      {
        name: "Typhon",
        level: 55,
        power: 35,
        health: 375,
        immune: ["water"],
        resistant: ["normal", "fire"],
        weakness: ["none"],
        neutral: ["earth"],
      },
    ],
    //random encounters below
    //need to change stats below
    golems: [
      {
        name: "Mecha Construct",
        level: 25,
        power: 35,
        health: 375,
        immune: ["earth"],
        resistant: ["fire", "water"],
        weakness: ["none"],
        neutral: ["normal"],
      },
      {
        name: "Flesh Golem",
        level: 25,
        power: 35,
        health: 375,
        immune: ["earth"],
        resistant: ["fire", "water"],
        weakness: ["none"],
        neutral: ["normal"],
      },
      {
        name: "Ice Golem",
        level: 25,
        power: 35,
        health: 375,
        immune: ["water"],
        resistant: ["normal"],
        weakness: ["fire"],
        neutral: ["earth"],
      },
    ],
    behemoth: [
      {
        name: "Behemoth",
        level: 25,
        power: 35,
        health: 375,
        immune: ["earth"],
        resistant: ["fire", "water"],
        weakness: ["none"],
        neutral: ["normal"],
      },
      {
        name: "Leviathan",
        level: 25,
        power: 35,
        health: 375,
        immune: ["earth"],
        resistant: ["fire", "water"],
        weakness: ["none"],
        neutral: ["normal"],
      },
      {
        name: "Bahamut",
        level: 25,
        power: 35,
        health: 375,
        immune: ["earth"],
        resistant: ["fire", "water"],
        weakness: ["none"],
        neutral: ["normal"],
      },
    ],
    titans: [
      {
        name: "Cronos",
        level: 25,
        power: 35,
        health: 375,
        immune: ["earth"],
        resistant: ["fire", "water"],
        weakness: ["none"],
        neutral: ["normal"],
      },
      {
        name: "Ymir",
        level: 25,
        power: 35,
        health: 375,
        immune: ["earth"],
        resistant: ["fire", "water"],
        weakness: ["none"],
        neutral: ["normal"],
      },
      {
        name: "Asura",
        level: 25,
        power: 35,
        health: 375,
        immune: ["earth"],
        resistant: ["fire", "water"],
        weakness: ["none"],
        neutral: ["normal"],
      },
    ],
  },
  boss: [
    {
      name: "Challenger",
      level: 25,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
    {
      name: "Normal stranger",
      level: 25,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
    {
      name: "Tubby Guard",
      level: 25,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
    {
      name: "Dumb, Dumber, and Dumbest",
      level: 25,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
  ],
};
export {
  monstersArea1,
  monstersArea2,
  monstersArea3,
  bossMonsters,
  allMonsters,
};
