// const monsters = [
//     {
//       name: "Fire Slime",
//       level: 5,
//       health: 15,
//       immune: "fire",
//       resistant: "earth",
//       weakness: "water",
//     },
//     {
//       name: "Water Slime",
//       level: 5,
//       health: 15,
//       immune: "water",
//       resistant: "fire",
//       weakness: "earth",
//     },
//     {
//       name: "Metal Slime",
//       level: 5,
//       health: 15,
//       immune: "earth",
//       resistant: "water",
//       weakness: "fire",
//     },
//     {
//       name: "Flame Wizard",
//       level: 10,
//       health: 50,
//       immune: "fire",
//       resistant: "earth",
//       weakness: "water",
//     },
//     {
//       name: "Ice Sorcerer",
//       level: 10,
//       health: 50,
//       immune: "water",
//       resistant: "fire",
//       weakness: "earth",
//     },
//     {
//       name: "Shaman",
//       level: 10,
//       health: 50,
//       immune: "earth",
//       resistant: "water",
//       weakness: "fire",
//     },
//     {
//       name: "Blaze Elemental",
//       level: 20,
//       health: 150,
//       immune: "fire",
//       resistant: "earth",
//       weakness: "water",
//     },
//     {
//       name: "Blizzard Elemental",
//       level: 20,
//       health: 150,
//       immune: "water",
//       resistant: "fire",
//       weakness: "earth",
//     },
//     {
//       name: "Earth Elemental",
//       level: 20,
//       health: 150,
//       immune: "earth",
//       resistant: "water",
//       weakness: "fire",
//     },
//   ];

const monsters = {
  slimes: [
    {
      name: "Fire Slime",
      level: 1,
      power: 5,
      health: 15,
      immune: ["fire"],
      resistant: ["earth"],
      weakness: ["water"],
      neutral: ["normal"],
    },
    {
      name: "Water Slime",
      level: 1,
      power: 5,
      health: 15,
      immune: ["water"],
      resistant: ["fire"],
      weakness: ["earth"],
      neutral: ["normal"],
    },
    {
      name: "Metal Slime",
      level: 2,
      power: 6,
      health: 20,
      immune: ["earth"],
      resistant: ["water"],
      weakness: ["fire"],
      neutral: ["normal"],
    },
  ],
  wizards: [
    {
      name: "Flame Wizard",
      level: 12,
      power: 20,
      health: 120,
      immune: ["fire"],
      resistant: ["earth"],
      weakness: ["water"],
      neutral: ["normal"],
    },
    {
      name: "Ice Sorcerer",
      level: 10,
      power: 16,
      health: 100,
      immune: ["water"],
      resistant: ["fire"],
      weakness: ["earth"],
      neutral: ["normal"],
    },
    {
      name: "Shaman",
      level: 11,
      power: 18,
      health: 110,
      immune: ["earth"],
      resistant: ["water"],
      weakness: ["fire"],
      neutral: ["normal"],
    },
  ],
  elementals: [
    {
      name: "Blaze Elemental",
      level: 20,
      power: 6,
      health: 200,
      immune: ["fire"],
      resistant: ["earth"],
      weakness: ["water"],
      neutral: ["normal"],
    },
    {
      name: "Blizzard Elemental",
      level: 20,
      power: 6,
      health: 200,
      immune: ["water"],
      resistant: ["fire"],
      weakness: ["earth"],
      neutral: ["normal"],
    },
    {
      name: "Earth Elemental",
      level: 20,
      power: 6,
      health: 200,
      immune: ["earth"],
      resistant: ["water"],
      weakness: ["fire"],
      neutral: ["normal"],
    },
  ],
  bandits: [
    {
      name: "Bandit Keith",
      level: 5,
      power: 6,
      health: 70,
      immune: ["none"],
      resistant: ["none"],
      weakness: ["none"],
      neutral: ["normal", "fire", "earth", "water"],
    },
    {
      name: "Quinn Eyepatch",
      level: 10,
      power: 6,
      health: 120,
      immune: ["none"],
      resistant: ["none"],
      weakness: ["none"],
      neutral: ["normal", "fire", "earth", "water"],
    },
    {
      name: "Kerry Crazy Eyes",
      level: 15,
      power: 6,
      health: 170,
      immune: ["none"],
      resistant: ["fire"],
      weakness: ["none"],
      neutral: ["normal", "earth", "water"],
    },
    {
      name: "Thieving Carmen",
      level: 20,
      power: 6,
      health: 230,
      immune: ["none"],
      resistant: ["earth"],
      weakness: ["none"],
      neutral: ["normal", "fire", "water"],
    },
  ],
  wolves: [
    {
      name: "Wolf Alpha",
      level: 5,
      power: 6,
      health: 75,
      immune: ["none"],
      resistant: ["earth"],
      weakness: ["fire"],
      neutral: ["normal", "water"],
    },
    {
      name: "Kiba",
      level: 10,
      power: 6,
      health: 150,
      immune: ["none"],
      resistant: ["earth"],
      weakness: ["fire"],
      neutral: ["normal", "water"],
    },
    {
      name: "White Fang",
      level: 15,
      power: 6,
      health: 275,
      immune: ["none"],
      resistant: ["earth"],
      weakness: ["fire"],
      neutral: ["normal", "water"],
    },
    {
      name: "Ranga",
      level: 20,
      power: 6,
      health: 375,
      immune: ["none"],
      resistant: ["earth"],
      weakness: ["none"],
      neutral: ["normal", "water", "fire"],
    },
  ],
  mimics: [
    {
      name: "Dark Mimic",
      level: 3,
      power: 6,
      health: 75,
      immune: ["none"],
      resistant: ["earth"],
      weakness: ["fire"],
      neutral: ["normal", "water"],
    },
    {
      name: "Mimighoul",
      level: 12,
      power: 18,
      health: 150,
      immune: ["none"],
      resistant: ["earth", "fire"],
      weakness: ["none"],
      neutral: ["normal", "water"],
    },
    {
      name: "Mimiking",
      level: 18,
      power: 35,
      health: 375,
      immune: ["earth"],
      resistant: ["fire", "water"],
      weakness: ["none"],
      neutral: ["normal"],
    },
  ],
};

export default monsters;
